// license-header java merge-point
//
// Generated by: MetafacadeLogicImpl.vsl in andromda-meta-cartridge.
package org.andromda.cartridges.angularjs.metafacades;

import java.util.Collection;
import java.util.Iterator;

import org.andromda.metafacades.uml.StateFacade;
import org.andromda.metafacades.uml.TransitionFacade;

/**
 * 
 * MetafacadeLogic implementation for org.andromda.cartridges.angularjs.metafacades.AngAction.
 *
 * @see org.andromda.cartridges.angularjs.metafacades.AngAction
 */
public class AngActionLogicImpl
    extends AngActionLogic
{
    private static final long serialVersionUID = 34L;
    /**
     * Public constructor for AngActionLogicImpl
     * @see org.andromda.cartridges.angularjs.metafacades.AngAction
     */
    public AngActionLogicImpl (Object metaObject, String context)
    {
        super(metaObject, context);
    }

    /**
     * 
     * @see org.andromda.cartridges.angularjs.metafacades.AngAction#getNextPage()
     */
    @Override
	public String handleGetNextPage() {

		String next="";
		StateFacade sf=null;
		System.out.println("===========================");
		if(this.hasStereotype(JSFProfile.ST_ANGACTION)){
			System.out.println("===========ST_ANGACTION================");
       Collection<TransitionFacade> inclist=this.getOutgoings();
            Iterator<TransitionFacade> i = inclist.iterator();
				while (i.hasNext())
				  {
					TransitionFacade saFacade = (TransitionFacade) i.next();
					 sf=(StateFacade) saFacade.getTarget();
					if(sf.hasStereotype(JSFProfile.ST_ANGVIEW)){
						System.out.println("1 level");
						System.out.println(sf.getName());
						next= sf.getName();
					}
					
	
	               }
				
				if(next.equals("")&&(sf!=null)){
					Collection<TransitionFacade> inclist2=sf.getOutgoings();
                      Iterator<TransitionFacade> i2 = inclist2.iterator();
							while (i2.hasNext()){
								
                               TransitionFacade saFacade2 = (TransitionFacade) i2.next();
								StateFacade sf2=(StateFacade) saFacade2.getTarget();
								if(sf2.hasStereotype(JSFProfile.ST_ANGVIEW)){
									System.out.println("2 level");
									System.out.println(sf2.getName());
									 next=sf2.getName();
								}
				  }
				  }
				
					
	}
		return next;
		}
}