// license-header java merge-point
//
// Generated by: MetafacadeLogicImpl.vsl in andromda-meta-cartridge.
package org.andromda.cartridges.angularjs.metafacades;

/**
 * <p>
 * Represents an operation for a JSF controller.
 * </p>
 * MetafacadeLogic implementation for org.andromda.cartridges.angularjs.metafacades.AngControllerOperation.
 *
 * @see org.andromda.cartridges.angularjs.metafacades.AngControllerOperation
 */
public class AngControllerOperationLogicImpl
    extends AngControllerOperationLogic
{
    private static final long serialVersionUID = 34L;
    /**
     * Public constructor for AngControllerOperationLogicImpl
     * @see org.andromda.cartridges.angularjs.metafacades.AngControllerOperation
     */
    public AngControllerOperationLogicImpl (Object metaObject, String context)
    {
        super(metaObject, context);
    }

    /**
     * <p>
     * The controller implementation operation signature that takes the
     * appropriate form (if this operation has at least one form field)
     * as an argument.
     * </p>
     * @see org.andromda.cartridges.angularjs.metafacades.AngControllerOperation#getImplementationFormSignature()
     */
    protected String handleGetImplementationFormSignature()
    {
        // TODO put your implementation here.
        return null;
    }

	@Override
	protected String handleGetOperationType() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	protected String handleGetFactoryName() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	protected String handleGetFactoryType() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	protected Object handleGetAngController() {
		// TODO Auto-generated method stub
		return null;
	}
}