// license-header java merge-point
//
// Generated by: MetafacadeLogicImpl.vsl in andromda-meta-cartridge.
package org.andromda.cartridges.angularjs.metafacades;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;

import org.andromda.cartridges.angularjs.metafacades.AngControllerLogic;
import org.andromda.metafacades.uml.ClassifierFacade;
import org.andromda.metafacades.uml.DependencyFacade;
import org.andromda.metafacades.uml.EventFacade;
import org.andromda.metafacades.uml.ModelFacade;
import org.andromda.metafacades.uml.OperationFacade;
import org.andromda.metafacades.uml.StateFacade;
import org.andromda.metafacades.uml.TransitionFacade;
import org.apache.commons.lang3.ObjectUtils;
import org.apache.commons.lang3.StringUtils;

/**
 * <p>
 * Represents a controller for a JSF application.
 * </p>
 * MetafacadeLogic implementation for org.andromda.cartridges.angularjs.metafacades.AngController.
 *
 * @see org.andromda.cartridges.angularjs.metafacades.AngController
 */
public class AngControllerLogicImpl
    extends AngControllerLogic
{
    private static final long serialVersionUID = 34L;
    /**
     * Public constructor for AngControllerLogicImpl
     * @see org.andromda.cartridges.angularjs.metafacades.AngController
     */
    public AngControllerLogicImpl (Object metaObject, String context)
    {
        super(metaObject, context);
    }

    /**
     * <p>
     * The implementation name of this controller.
     * </p>
     * @see org.andromda.cartridges.angularjs.metafacades.AngController#getImplementationName()
     */
    protected String handleGetImplementationName()
    {
        // TODO put your implementation here.

        return "";
    }

	@Override
	protected List handleGetSessionObjectReferences() {
		// TODO Auto-generated method stub
		return new ArrayList();
	}

	@Override
	protected Collection handleGetControllerOperation() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	protected Object handleGetAngControllerOperation() {
		// TODO Auto-generated method stub
		return null;
	}

//	@Override
//	protected String handleGetMasterFactory() {
//
//		
//		if(this.findTaggedValue(JSFProfile.TAGGEDVALUE_ANGCONTROLLER_MASTERFACTORY)!=null){	
//		
//			String val=this.findTaggedValue(JSFProfile.TAGGEDVALUE_ANGCONTROLLER_MASTERFACTORY).toString();
//			return Character.toString(val.charAt(0)).toUpperCase()+val.substring(1);
//		}else{
//				return "Undefined";
//			}
//		
//	}

	@Override
	protected Object handleGetAngFactory() {
		// TODO Auto-generated method stub
       Collection  col = getAssociatedClasses();
		System.out.println("================");
		ClassifierFacade cf=null;
		Iterator itt=col.iterator();
		while(itt.hasNext()){
			System.out.println("================");
		 cf=(ClassifierFacade) itt.next();
	        return cf;
		
		}
				
		return cf;
	}

	@Override
	protected Collection handleGetViews() {
		// TODO Auto-generated method stub
		Collection  col = getAssociatedClasses();
		return col;
	}





}