// license-header java merge-point
//
// Generated by: MetafacadeLogicImpl.vsl in andromda-meta-cartridge.
package org.andromda.cartridges.angularjs.metafacades;

/**
 * 
 * MetafacadeLogic implementation for org.andromda.cartridges.angularjs.metafacades.AngModel.
 *
 * @see org.andromda.cartridges.angularjs.metafacades.AngModel
 */
public class AngModelLogicImpl
    extends AngModelLogic
{
    private static final long serialVersionUID = 34L;
    /**
     * Public constructor for AngModelLogicImpl
     * @see org.andromda.cartridges.angularjs.metafacades.AngModel
     */
    public AngModelLogicImpl (Object metaObject, String context)
    {
        super(metaObject, context);
    }
}